### ISSUE TITLE
Store job outputs on Azure

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/simulate#57] opened 2018-05-10 10:36 UTC
## Goal 
1. Zip file and upload directory into Azure blob storage when OpenF job finishes

## Acceptance criteria
1. Blob named with job id
1. File uploaded
1. Send request to job manager to change job status
1. Job manager changes status 

## Out of scope
1. Store output URI in middleware db

**Comment by masonlr** [comment] 2018-09-21 09:00
Duplicate of #81.

**Closed by masonlr** 2018-09-21 09:00 UTC
