### ISSUE TITLE
Deploy to Azure

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/simulate#63] opened 2018-06-04 09:14 UTC
## Goal 
To deploy docker onto Azure

## Acceptance criteria
Gateway accessible on Azure site

## Implementation notes
1) 
2)

**Comment by masonlr** [comment] 2018-09-21 08:59
Duplicate of https://github.com/alan-turing-institute/simulate/issues/86.

**Closed by masonlr** 2018-09-21 08:59 UTC
